/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gradle.builds.Java.projects;

public class App {
    public String getGreeting() {

        return "This is a Gradle Projec";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }
}
